[package]
name = "mvrp"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = "0.14"
hyper-tls = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.22"
rustls = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
fs-extra = "1.0"
